name: emulators
description: A utility library to automate mobile emulators. Wraps `xcrun` for iOS and the Android CLI tools.
version: 0.4.10
repository: https://github.com/tim-smart/dart_emulators.git

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  fpdt: ^0.0.59
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.0.4
  flutter_lints: ^2.0.1
  freezed: ^2.0.3
  json_serializable: ^6.0.1
